googleAnalytics = "G-FBHSKM2KST"

baseURL = 'https://nathangillispie.work/'
languageCode = 'en-us'
title = 'Nathan Gillispie'

enableGitInfo = false

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[outputs]
  home = ['html']
  section = ['html', 'rss']
  term = ['html']

[services]
  [services.rss]
    limit = 20

copyright = 'Â© 2023 ABC Widgets, Inc.'

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'auto'


  # (Optional, default true) Start and end levels can be controlled with markup.tableOfContents setting.
  BookToC = false

  # (Optional, default true) Enables comments template on pages
  # By default partials/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = false

  BookDateFormat = "02 Jan 2006"
  [params.author]
    email = 'feed@nathangillispie.work'
    name = 'Nathan G'